### ISSUE TITLE
Text to audio and Image generation

### ISSUE THREAD

**Issue by ghost** [ck3d/nix-local-ai#1]
Compilation with available [GO_TAGS](https://github.com/mudler/LocalAI/blob/1c57f8d07704aa6449b7c2c44ecf436e47af4756/Makefile#L130)

**Comment by ck3d** [comment]
I prepared the switches, but non of them are working right now:
https://github.com/ck3d/nix-local-ai/commit/df86c51924b86f543b9c686a76c773e4a69eb21f

**Comment by ck3d** [comment]
local-ai builds now for all possible values of GO_TAGS.
