### ISSUE TITLE
`with_clblas` seems broken

### ISSUE THREAD

**Issue by ulrikstrid** [ck3d/nix-local-ai#4]
When running with `with_clblas` flag enable I get the following error:
`/nix/store/gl7h4kwkjh2vzqi8y87gd4nsymd2wah9-local-ai-2.9.0/bin/local-ai: error while loading shared libraries: libOpenCL.so.1: cannot open shared object file: No such file or directory`

This might be user error, I'm on NixOS and have these options in my config:
```nix
  hardware.opengl.extraPackages = with pkgs; [
    rocmPackages.clr.icd
    rocmPackages.rocm-runtime
  ];
  hardware.opengl.enable = true;
  systemd.tmpfiles.rules = [
    "L+    /opt/rocm/hip   -    -    -     -    ${pkgs.rocmPackages.clr}"
  ];
  ```

**Comment by ck3d** [comment]
Thanks, I fixed the issue with commit:
https://github.com/ck3d/nix-local-ai/commit/ea9d3e735103c5582ae7301a797bc7af61938557
